
use AdventureWorks2014
go

SELECT 'AdventureWorks2014' AS DBNAME, 'STORED PROCEDURE' AS OBJ_TYPE, ROUTINE_SCHEMA + '.' + ROUTINE_NAME AS OBJ_NAME
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_TYPE = 'PROCEDURE'
UNION ALL
SELECT 'AdventureWorks2014' AS DBNAME, 'FUNCTION' AS OBJ_TYPE, ROUTINE_SCHEMA + '.' + ROUTINE_NAME AS OBJ_NAME
FROM INFORMATION_SCHEMA.ROUTINES 
WHERE ROUTINE_TYPE = 'FUNCTION'
UNION ALL
SELECT 'AdventureWorks2014' AS DBNAME, 'TABLE' AS OBJ_TYPE, TABLE_SCHEMA + '.' + TABLE_NAME AS OBJ_NAME
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE'
UNION ALL
SELECT 'AdventureWorks2014' AS DBNAME, 'VIEWS' AS OBJ_TYPE, TABLE_SCHEMA + '.' + TABLE_NAME AS OBJ_NAME
FROM INFORMATION_SCHEMA.VIEWS
UNION ALL
SELECT 'AdventureWorks2014' AS DBNAME, 'SCHEMA' AS OBJ_TYPE, [SCHEMA_NAME] AS OBJ_NAME
FROM INFORMATION_SCHEMA.SCHEMATA
UNION ALL
SELECT 'AdventureWorks2014' AS DBNAME, 'SEQUENCES' AS OBJ_TYPE, SEQUENCE_SCHEMA + '.' + SEQUENCE_NAME AS OBJ_NAME
FROM INFORMATION_SCHEMA.SEQUENCES
UNION ALL
SELECT 'AdventureWorks2014' AS DBNAME, 'SQL_TRIGGER' AS OBJ_TYPE, [name] AS OBJ_NAME
FROM sys.objects WHERE type IN ('TR')
ORDER BY OBJ_TYPE, OBJ_NAME